//
// Generated by JTB 1.3.2
//

package org.andwellness.config.grammar.visitor;
import org.andwellness.config.grammar.syntaxtree.NodeList;
import org.andwellness.config.grammar.syntaxtree.NodeListOptional;
import org.andwellness.config.grammar.syntaxtree.NodeOptional;
import org.andwellness.config.grammar.syntaxtree.NodeSequence;
import org.andwellness.config.grammar.syntaxtree.NodeToken;
import org.andwellness.config.grammar.syntaxtree.condition;
import org.andwellness.config.grammar.syntaxtree.conjunction;
import org.andwellness.config.grammar.syntaxtree.expr;
import org.andwellness.config.grammar.syntaxtree.id;
import org.andwellness.config.grammar.syntaxtree.sentence;
import org.andwellness.config.grammar.syntaxtree.sentence_prime;
import org.andwellness.config.grammar.syntaxtree.start;
import org.andwellness.config.grammar.syntaxtree.value;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> sentence()
    * f1 -> <EOF>
    */
   public void visit(start n);

   /**
    * f0 -> expr() sentence_prime()
    *       | "(" sentence() ")" sentence_prime()
    */
   public void visit(sentence n);

   /**
    * f0 -> ( conjunction() sentence() sentence_prime() )?
    */
   public void visit(sentence_prime n);

   /**
    * f0 -> id()
    * f1 -> condition()
    * f2 -> value()
    */
   public void visit(expr n);

   /**
    * f0 -> <TEXT>
    */
   public void visit(id n);

   /**
    * f0 -> "=="
    *       | "!="
    *       | "<"
    *       | ">"
    *       | "<="
    *       | ">="
    */
   public void visit(condition n);

   /**
    * f0 -> <TEXT>
    */
   public void visit(value n);

   /**
    * f0 -> "and"
    *       | "or"
    */
   public void visit(conjunction n);

}

