//
// Generated by JTB 1.3.2
//

package org.andwellness.grammar.syntaxtree;

/**
 * Grammar production:
 * f0 -> conjunction() expr()
 *       | <EOF>
 */
public class sentence_prime implements Node {
   public NodeChoice f0;

   public sentence_prime(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(org.andwellness.grammar.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.andwellness.grammar.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.andwellness.grammar.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.andwellness.grammar.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

