//
// Generated by JTB 1.3.2
//

package org.andwellness.grammar.syntaxtree;

/**
 * Grammar production:
 * f0 -> expr()
 * f1 -> sentence_prime()
 */
public class sentence implements Node {
   public expr f0;
   public sentence_prime f1;

   public sentence(expr n0, sentence_prime n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(org.andwellness.grammar.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.andwellness.grammar.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.andwellness.grammar.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.andwellness.grammar.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

